[tox]
envlist = py27

[testenv]
deps = -rrequirements-dev.txt
commands = py.test

[flake8]
exclude = static/*,templates/*
ignore = D200,D203,D204,E128,E251

[pep257]
verbose = true
ignore = D200,D203,D204
explain = true
